### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by zhufx** [readium/readium-sdk#181] opened 2015-07-06 12:48 UTC
When I build readium-sdk. It cames out this problem:

LINUX_ADT_NDK/android-ndk-r10e/platforms/android-19/arch-arm/usr/include -c  ./../../ePub3/xml/utilities/base.cpp -o /home/lanruotian/java_workspace/github/SDKLauncher-Android/readium-sdk/Platform/Android/obj/local/armeabi-v7a/objs-debug/epub3/ePub3/xml/utilities/base.o 
make: Leaving directory `/home/lanruotian/java_workspace/github/SDKLauncher-Android/readium-sdk/Platform/Android'
./../../ePub3/xml/utilities/base.h:37:29: fatal error: libxml/xmlerror.h: No such file or directory
 #include <libxml/xmlerror.h>
                             ^
compilation terminated.

How to fix this? Thank you for answer. :)

**Comment by danielweck** [comment] 2015-07-07 09:57
What is the command line you run in your shell? (it should look like: `ndk-compile.sh build /PATH.TO.NDK.FOLDER`)

**Comment by zhufx** [comment] 2015-07-08 03:39
Thanks for you answer:)

Here is some screenshot for build problem, I have run correct command line in my shell.

![2015-07-08 11 08 02](https://cloud.githubusercontent.com/assets/10691415/8562539/b90cc878-2565-11e5-806d-d8019e9cc70d.png)

![2015-07-08 11 09 04](https://cloud.githubusercontent.com/assets/10691415/8562543/be59e6c6-2565-11e5-91e9-44c519d55179.png)

OS:Ubuntu 14.10

**Comment by danielweck** [comment] 2015-07-08 15:13
Could you install zsh `sudo apt-get install zsh` and try again please?
Possibly duplicate of https://github.com/readium/readium-sdk/issues/47
(please report back in the original issue #47)

**Closed by danielweck** 2015-07-08 15:13 UTC
Labels: Android, priority medium, question

**Comment by zhufx** [comment] 2015-07-09 08:37
@danielweck Thanks for your help! I have build redium-sdk and SDKLauncher-Android Project successfully ! 

There is one point ,  SDKLauncher-Android Project can't work on Gennymotion virtual device ! Problem could be ‘ can't load epub3 library ’ ! However , it work on real android device well ! It waste me a lot of time . I think we could  write a notification on README.md  for developer to avoid this .

Forgive my poor English .  I try my best ...

**Comment by danielweck** [comment] 2015-07-09 09:14
@zhufx thanks for your feedback!
If I am not mistaken, Genymotion is a `x86` emulator (your hardware device is probably `arm`). You must therefore use the `android-NDK-x86` feature branch to compile the Readium SDK and the Android application:
https://github.com/readium/SDKLauncher-Android/tree/feature/android-NDK-x86/
https://github.com/readium/readium-sdk/tree/feature/android-NDK-x86/

**Comment by outsideMyBox** [comment] 2015-12-11 21:55
Hi,
The links in the previous comment are not valid anymore. 
I've tried to compile the last version (0.21) myself but even after getting, adapting and compiling the dependencies (based partly on the steps described at http://wudev.digitaltorque.com/2014/03/building-readium-for-x86-android.html) I still face errors. 
Before going further, Is there a simple way to compile or get the Readium SDK for x86?

Thanks

**Comment by danielweck** [comment] 2015-12-11 21:57
The Android Readium app compiles for both ARM and X86, have you tried the develop branch?

**Comment by outsideMyBox** [comment] 2015-12-11 23:08
No, I had cloned the master branch to use a stable one (which didn't contain the x86 target in Application.mk). I tried with the develop branch (0.22.1) and it works fine.

Shouldn't the READMEs be updated? For example the main one refers to the version 0.14 and the Android NDK r8e. Using r8e doesn't work, I had to run ndk-compile.sh with android-ndk-r10e.
The README under Platform/Android is not up-to-date either.

But thanks anyway, It works now!

**Comment by danielweck** [comment] 2015-12-12 10:23
Agreed, the documentation needs updating. Hopefully some resources will be available early next year to sort this out.

Related note: as you know there is an ongoing transition (generally-speaking, not specific to Readium) from Eclipse to Android Studio (Gradle), and a few developers have been contributing feedback and code here on GitHub. The main challenge is the native Readium C++ library (and the NDK code layer) which requires Bash build scripts (to prepare the headers and to compile), as well as some symbolinc linking magic for submodule integration...which in turn means that the dev story on Windows is not great. I assume you're on OSX or Linux?

**Comment by outsideMyBox** [comment] 2015-12-15 15:28
I use Linux. I still have an issue though as the target x86 compiles to 32 bits whereas I need 64 bits. I tried to change APP_ABI := x86_64 in Application.mk but there is no 64 bit version of icu4c, open-ssl and Boost. I managed to compile  icu4c, open-ssl  for 64 bits but still have errors for Boost.

**Comment by danielweck** [comment] 2016-01-09 19:10
@outsideMyBox the master branch should now compile both x86/32-bit and 64-bit binaries (the develop branch was recently merged in).

**Comment by danielweck** [comment] 2016-06-09 15:44
@outsideMyBox could you explain how you compiled `icu4c` for ARM64? (please answer in this new issue:
https://github.com/readium/readium-sdk/issues/245
)
PS: Boost is not required anymore! (so we only need arm64-v8a static libs for OPENSSL and ICU4C)
Many thanks! :)
