### ISSUE TITLE
Error:Execution failed for task ':app:buildEpubReadingSystem_Git'. > A problem occurred starting process 'command 'git''

### ISSUE THREAD

**Issue by gibumkim** [readium/readium-sdk#252] opened 2016-07-05 06:01 UTC
![error](https://cloud.githubusercontent.com/assets/15388826/16575199/41a23d8e-42c1-11e6-9b4a-1403356dbcf4.png)

android studio build error..!

os windows7

**Comment by gibumkim** [comment] 2016-07-05 08:48
complete..

build_epubReadingSystem.gradle

file edit

def getCommandOutput(cwd, cmd) {
def stdout = new ByteArrayOutputStream()
return stdout.toString().trim()
}

AND

android SDK,NDK,GIT The exact settings required confirmation

**Comment by danielweck** [comment] 2016-07-05 10:19
Hello @gibumkim 
I do not understand your second comment. Could you please clarify?

This is the current code:
https://github.com/readium/SDKLauncher-Android/blob/develop/SDKLauncher-Android/app/build_epubReadingSystem.gradle
```gradle
def getCommandOutput(cwd, cmd) {
    def stdout = new ByteArrayOutputStream()

    exec {
        workingDir = cwd
        commandLine = cmd
        standardOutput = stdout
    }

    return stdout.toString().trim()
}
```

**Comment by gibumkim** [comment] 2016-07-06 00:48
![error](https://cloud.githubusercontent.com/assets/15388826/16604288/b5cf4e3e-435e-11e6-89f0-844c0470d3d1.png)

    exec {
        workingDir = cwd
        commandLine = cmd
        standardOutput = stdout
    }

When you add the error.

**Comment by gibumkim** [comment] 2016-07-06 00:54
![error](https://cloud.githubusercontent.com/assets/15388826/16604336/10a6a802-435f-11e6-9d19-23ecf65f4198.png)

-------------------------------------------------------------------------------------------------------------------------------
Error:fatal: Not a git repository (or any of the parent directories): .git
FAILURE: Build failed with an exception.

* Where:
Script 'D:\SDKLauncher-Android\SDKLauncher-Android\app\build_epubReadingSystem.gradle' line: 6

* What went wrong:
Execution failed for task ':app:buildEpubReadingSystem_Git'.
> Process 'command 'git'' finished with non-zero exit value 128

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

-------------------------------------------------------------------------------------------------------------------------------

    exec {
        workingDir = cwd
        commandLine = cmd
        standardOutput = stdout
    }

1. CODE ADD : Build  Error
2. CODE DELETE : Build Success

**Comment by yogis7997** [comment] 2016-10-17 10:54
![image](https://cloud.githubusercontent.com/assets/14258044/19435011/2c5179b0-9486-11e6-993d-6248dda90cc9.png)
Getting same issue. Please help.

**Comment by danielweck** [comment] 2016-10-17 14:34
Have you installed Git from https://git-for-windows.github.io or https://git-scm.com/downloads (GitHub: https://github.com/git-for-windows/git/releases)

**Comment by yogis7997** [comment] 2016-10-18 04:52
yes i  have installed git from https://git-for-windows.github.io.

**Comment by danielweck** [comment] 2016-10-18 07:26
I assume you correctly checked-out the develop branch of all git repositories / submodules? 
SDKLauncher-Android
readium-sdk
readium-shared-js
?
What does 'git status' say in each of them, from the command line? (GitBash, or regular MS-DOS shell)

**Comment by yogis7997** [comment] 2016-10-19 06:47
Yes i have followed all step mentioned. 

Below is git status:

1.  ysharma@ysharma MINGW64 ~/desktop/test/SDKLauncher-Android/readium-sdk (master)
    $ git status
   On branch master
   Your branch is up-to-date with 'origin/master'.
   nothing to commit, working tree clean

2. ysharma@ysharma MINGW64 ~/desktop/test/SDKLauncher-Android/readium-shared-js (master)
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

**Comment by danielweck** [comment] 2016-10-19 07:15
sdklauncher-android also on master?

**Comment by yogis7997** [comment] 2016-10-19 07:43
Yes

ysharma@ysharma MINGW64 ~/desktop/test/SDKLauncher-Android (master)
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   SDKLauncher-Android/app/src/main/assets/readium-shared-js/epubReadingSystem.js
        modified:   readium-shared-js (new commits)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        SDKLauncher-Android/gradle.properties

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by danielweck** [comment] 2016-11-02 09:06
Okay, please don't let this build error get in the way of getting other things done. The ePubReadingSystem versioning info is useful, but in your case you can probably live without it.
Simply invoke the command: `git checkout SDKLauncher-Android/app/src/main/assets/readium-shared-js/epubReadingSystem.js` to restore the empty template.
Then, comment out the Gradle scripts:
https://github.com/readium/SDKLauncher-Android/blob/master/SDKLauncher-Android/app/build.gradle#L43
`apply from: 'build_epubReadingSystem.gradle'`
and
https://github.com/readium/SDKLauncher-Android/blob/master/SDKLauncher-Android/app/build.gradle#L51
`"buildEpubReadingSystem"`

**Comment by AkshayTannirwar** [comment] 2018-06-01 10:46
Hi daniel,
 i am facing this issue can u help

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:buildEpubReadingSystem_Git'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:196)
	at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:193)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:193)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:50)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:43)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:75)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'git''
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:198)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:329)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:86)
	... 5 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'git'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WindowsProcessLauncher.start(WindowsProcessLauncher.java:22)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:68)
	... 5 more
Caused by: java.io.IOException: Cannot run program "git" (in directory "D:\ITC\SDKLauncher-Android"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 8 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 9 more

**Comment by AkshayTannirwar** [comment] 2018-06-01 10:48
sdklauncher-android also on origin/master

**Comment by AkshayTannirwar** [comment] 2018-06-01 11:09
sdklauncher-android also on origin/develop

**Comment by AkshayTannirwar** [comment] 2018-06-01 11:57
can u help me build this project with old gradle build

**Comment by danielweck** [comment] 2018-06-06 12:33
@llemeurfr FYI I replied to @AkshayTannirwar in his cross-posted issue:
https://github.com/readium/SDKLauncher-Android/issues/141

**Comment by danielweck** [comment] 2018-06-06 12:35
Closing this old issue, same resolution as https://github.com/readium/SDKLauncher-Android/issues/141#issuecomment-394299584

**Closed by danielweck** 2018-06-06 12:35 UTC
Labels: difficulty:Dev, func:Builds, platform:Android, priority:High, type:Discussion
