### ISSUE TITLE
Error compiling Readium in Android Studio

### ISSUE THREAD

**Issue by rkwright** [readium/readium-sdk#180] opened 2015-07-03 16:29 UTC
From the IDPF Forum, jojoth, http://idpf.org/forum/topic-2509

I'm import readium_SDK_Test_Android in android studio follow https://github.com/readium/SDKLauncher-Android
So I have error when run::

Error:Execution failed for task ':ePub3Library:compileReleaseNdk'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/pong/Library/Android/ndk-r10e/ndk-build'' finished with non-zero exit value 2
Some body have any solution

Thank for advance,
sukat

PS. I'm not good abut writing.

**Comment by danielweck** [comment] 2015-07-03 19:30
Related issue:

https://github.com/readium/SDKLauncher-Android/issues/61

Note that @JCCR managed to convert the Eclipse project to Gradle / Android Studio, but I think that the native readium-sdk lib (including the JNI bits) was built via the command line (ndk-compile.sh) which takes care of all the peripheral setup / prepare tasks (such as copying the headers across, etc.).

**Comment by jojoth** [comment] 2015-07-13 08:06
Thank you  daniel and ekwright now  I make them to jar file follow by http://wudev.digitaltorque.com/2014/03/building-readium-for-x86-android.html
 But  anywhere have sample or tutorial about how to use it.
Thank you for advance

**Comment by danielweck** [comment] 2015-07-13 10:29
@jojoth I successfully use these feature branches:

**Comment by TienHai** [comment] 2015-09-10 08:33
@jojoth Hello, I successfully compil readium sdk and android launcher app.

we need
1. download latest android studio
2. from studio install `Android SDK Tools`, `Android SDK Platforms-tools` and `Android SDK Build-tools`. Install SDK Platform >= 4.1.2
3. download NDK r10e
4. download readium-sdk, readium-shared-js and SDKLauncher-Android. branch develop

compil epub3library
1. open studio, make a new project
 Application name : EPub3Library
 Company domain : android.sdk.readium.org
 Package name : org.readium.sdk.android
 Minium SDK : API 16 Android 4.1
 Add no activity.
2. `File > New > New module` and choose `Android Library`
 Application name : Library
 Module name : ePub3-Library
 Company domain : android.sdk.readium.org
 Package name : org.readium.sdk.android
 Minium SDK : API 16 Android 4.1
 Add no activity
3. delete `app` module, `File > Project Structure`. studio no delete folder `app`, delete it
delete `[PROJECT_DIR]/app`
 delete `[PROJECT_DIR]/[LIB_DIR]/src/androidTest`
delete `[PROJECT_DIR]/[LIB_DIR]/src/main/res/*`
4.  `File > Projet structure`, `SDK Location`, `Android NDK location` put ndk path
5. in file `[PROJECT_DIR]/[LIB_DIR]/src/main/AndroidManifest.xml` delete section application
6. in file `[LIB_DIR]/build.grable`, add in `android`, `defaultConfig`

ndk {
           moduleName "libepub3"
       }


in  `android` add


        sourceSets.main {
            jni.srcDirs = [] // disable automatic ndk-build call
        }

        task makeHeaders(type: Exec, description: 'Copy headers source') {
            commandLine './MakeHeaders.sh', 'Android'
        }

        task ndkBuild(type: Exec, dependsOn: 'makeHeaders', 
                description: 'Compile JNI source via NDK') {
            commandLine 'ndk-build',
                    '-C',
                    file('src/main').absolutePath,
                    'V=1',
                    'NDK_APPLICATION_MK=Application.mk',
                    'NDK_PROJECT_PATH=build',
                    'APP_BUILD_SCRIPT=Android.mk',
                    'NDK_DEBUG=1'
        }

        task ndkToJar(type: Zip, dependsOn: 'ndkBuild', 
                description: 'Create a JAR of the native libs') {
            destinationDir new File(buildDir, 'libs')
            baseName 'epub3-library'
            extension 'jar'
            from fileTree(dir: 'src/main/build/libs', include: '**/*')
            into 'lib/'
        }

        tasks.withType(JavaCompile) {
            compileTask -> compileTask.dependsOn ndkToJar
        }

in `dependencies` modifie libs path

        dependencies {
            compile fileTree(dir: 'build/libs', include: ['*.jar'])
            compile 'com.android.support:appcompat-v7:22.2.1'
        }


7. copy files

- copy `readium-sdk/Platform/Android/src/org` > `[PROJECT_DIR]/[LIB_DIR]/src/main/java`
- copy `readium-sdk/Platform/Android/jni` > `[PROJECT_DIR]/[LIB_DIR]/src/main`
- copy `readium-sdk/ePub3` > `[PROJECT_DIR]/[LIB_DIR]`
- copy `readium-sdk/MakeHeaders.sh` > `[PROJECT_DIR]/[LIB_DIR]`
 replace `Platform/"$1"/MakeHeaders.sh` by 

    [[ -d "src/main/include" ]] || {
            src/main/MakeHeaders.sh
        }

don't forget add right executable

- copy `readium-sdk/Platform/Android/Application.mk`  > `[PROJECT_DIR]/[LIB_DIR]/src/main`
- copy `readium-sdk/Platform/Android/prefix.h` > `[PROJECT_DIR]/[LIB_DIR]/src/main`
8. `Build` > `Make Project`

**Comment by TienHai** [comment] 2015-09-10 09:00
Now for SDKLauncher

1. In studio create a new project
Application name : SDKLauncher
Company domain : android.sdk.readium.org
Package name : org.readium.sdk.android
Minium SDK : API 16 Android 4.1
Add no activity
2. delete `[PROJECT_DIR]/app/src/androidTest`
3. delete `[PROJECT_DIR]/app/src/main/res/*`
4. copy files
- copy `SDKLauncher-Android/SDKLauncher-Android/src` > `[PROJECT_DIR]/app/src/main/java`
- copy `SDKLauncher-Android/SDKLauncher-Android/res` > `[PROJECT_DIR]/app/src/main/res`
- copy `SDKLauncher-Android/SDKLauncher-Android/AndroidManifest.xml` > `[PROJECT_DIR]/app/src/main`
-  copy `SDKLauncher-Android/SDKLauncher-Android/libs` > `[PROJECT_DIR]/app`
- copy `SDKLauncher-Android/SDKLauncher-Android/assets` > `[PROJECT_DIR]/app/src/main`
- copy `readium-shared-js/build-output/css` > `[PROJECT_DIR]/app/src/main/assets/readium-shared-js/builds/css`
- copy `readium-shared-js/build-output/_multiple-bundles` > `[PROJECT_DIR]/app/src/main/assets/readium-shared-js/builds/multiple-bundle`
- copy `readium-shared-js/build-output/_single-bundle` > `[PROJECT_DIR]/app/src/main/assets/readium-shared-js/builds/single-bundle`


configure grabble, add path to epub3library
1. open `[PROJECT_DIR]/setting.grable` and add

    include ':app'
    include ':Epub3Library'
    project(':Epub3Library').projectDir = 
        new File(settingsDir, '../Epub3Library/ePub3-Library')


configure module app
1.  in file  `[PROJECT_DIR]/app/build.grable`, modify `dependencies` and add `configurations`

    configurations {
        all*.exclude group: 'com.android.support', module: 'support-v4'
    }

    dependencies {
        compile project(path: ':epub3library')
        compile fileTree(dir: 'libs', include: ['*.jar'])
    }

Build > Make Project

**Comment by danielweck** [comment] 2015-09-11 08:49
@TienHai that's an awesome step-by-step guide, thanks!
I wonder how this compares with Montano's Gradle setup:
https://github.com/readium/readium-sdk/pull/198/files#diff-a168633d10f4ca9d28f1fae36331b4c4
(scroll down to see the other Gradle files)

**Comment by Lylicfuture** [comment] 2015-10-12 02:14
Hello @TienHai,thanks for your step-by-step guide.But I've met some problems when I am compiling compil epub3library.Can you help me to fix it?
![qq 20151012101657](https://cloud.githubusercontent.com/assets/15081611/10420588/de620cf0-70c9-11e5-8b04-169156b073af.jpg)

**Comment by danielweck** [comment] 2015-10-12 07:44
@Lylicfuture can you try running `MakeHeaders.sh` directly from your Bash / Cygwin shell? It is located in `readium-sdk/Platform/Android/` https://github.com/readium/readium-sdk/blob/develop/Platform/Android/MakeHeaders.sh

**Comment by TienHai** [comment] 2015-10-12 09:03
Hi @Lylicfuture 

The scritp "MakeHeaders.sh" copy the header files from ePub3/ThirdParty in "src/main/includes".
Exist 2 files "MakeHeaders.sh" 
 - readium-sdk/MakeHeaders.sh
 - readium-sdk/Platform/Android/MakeHeaders.sh

Copy the first in > [PROJECT_DIR]/[LIB_DIR] and replace Platform/"$1"/MakeHeaders.sh by

[[ -d "src/main/include" ]] || {
src/main/MakeHeaders.sh
}

for the second, I see, I forget in tuto we have to copy readium-sdk/Platform/Android/MakeHeaders.sh > [PROJECT_DIR]/[LIB_DIR]/src/main (I have update the tuto, thansk) .

**Comment by Lylicfuture** [comment] 2015-10-14 01:07
@danielweck I am afraid I can not running MakeHeaders.sh directly from my Cygwin shell.The feedback I get from Cygwin is that 
![qq 20151014090339](https://cloud.githubusercontent.com/assets/15081611/10472353/fc518efa-7251-11e5-89d2-98d0c2fb9fee.jpg).It seems the interpreter is wrong.

**Comment by danielweck** [comment] 2015-10-14 16:51
Have you tried (re)installing `zsh`?

**Comment by Lylicfuture** [comment] 2015-10-15 00:31
thanks @danielweck，now I can run MakeHeaders.sh directly from cygwin.But when I buile the project in Andrid studio the same question exist.
![1](https://cloud.githubusercontent.com/assets/15081611/10501742/0621fe9a-7317-11e5-8e5d-a801ae44d31b.jpg)

**Comment by TienHai** [comment] 2015-10-15 08:57
@Lylicfuture 

Did you retry running MakeHeaders.sh directly?

**Comment by Lylicfuture** [comment] 2015-10-15 10:46
Hello @TienHai.I have tried it several times ,it works well.

**Comment by TienHai** [comment] 2015-10-15 10:52
@Lylicfuture 

Did you try running ePub3-Library/MakeHeaders.sh directly? 
or ePub3-Library/src/main/MakeHeaders.sh?

**Comment by Lylicfuture** [comment] 2015-10-15 11:00
@TienHai I have tried them both.they both work well

**Comment by TienHai** [comment] 2015-10-15 12:25
@Lylicfuture 

Can we show your build.grable file in ePub3-Library directory?

**Comment by Lylicfuture** [comment] 2015-10-15 12:30
@TienHai .OK no problem.
here I post below:

import com.android.build.gradle.internal.dsl.ProductFlavor

apply plugin: 'com.android.library'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    final def config = defaultConfig {
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        ndk {
            moduleName "libepub3"
        }
    }
    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        ndk {
            moduleName "libepub3"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets.main {
        jni.srcDirs = [] // disable automatic ndk-build call
    }

    task makeHeaders(type:Exec,description:'Copy headers source') {
        commandLine './MakeHeaders.sh', 'Android'
    }

    task ndkBuild(type: Exec, dependsOn: 'makeHeaders', 
            description: 'Compile JNI source via NDK') {
        commandLine 'ndk-build',
                '-C',
                file('src/main').absolutePath,
                'V=1',
                'NDK_APPLICATION_MK=Application.mk',
                'NDK_PROJECT_PATH=build',
                'APP_BUILD_SCRIPT=Android.mk',
                'NDK_DEBUG=1'
    }

    task ndkToJar(type: Zip, dependsOn: 'ndkBuild', 
            description: 'Create a JAR of the native libs') {
        destinationDir new File(buildDir, 'libs')
        baseName 'epub3-library'
        extension 'jar'
        from fileTree(dir: 'src/main/build/libs', include: '**/*')
        into 'lib/'
    }

    tasks.withType(JavaCompile) {
        compileTask -> compileTask.dependsOn ndkToJar
    }
}

dependencies {
    compile fileTree(dir: 'build/libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.+'
}

**Comment by TienHai** [comment] 2015-10-15 12:46
@Lylicfuture 

All look fine, 
try compil with option "--stacktrace"
In studio : "File" > "Settings" > "Build, Execution, Deployment" > "Compiler"
add "--stacktrace" in Comande-line Options.

**Comment by Lylicfuture** [comment] 2015-10-15 13:04
@TienHai here is the result of stacktrace.
![1](https://cloud.githubusercontent.com/assets/15081611/10514424/31c63020-7380-11e5-9fe4-26a41ded421d.jpg)

**Comment by TienHai** [comment] 2015-10-15 13:57
@Lylicfuture 

Are the file ePub3-Library/MakeHeaders.sh  is executable ?
and the file ePub3-Library/src/main/MakeHeaders.sh is executable ?

try in you build.grable:

task makeHeaders(type:Exec,description:'Copy headers source') {
    commandLine '/bin/bash','MakeHeaders.sh', 'Android'
}

replace '/bin/bash' by your path to bash

**Comment by Lylicfuture** [comment] 2015-10-16 01:07
@TienHai thanks.Now the task makeheaders can pass.but task ndkBuild have problems too.Maybe I should use my ndk-build path to replace the "ndk-build"  too.I am trying now

**Comment by TienHai** [comment] 2015-10-16 07:58
@Lylicfuture 
Great, maybe you can modify your path to add ndk path and sdk tool path ?
export PATH=$PATH:/home/tien/Devel/Android/Ndk:/home/tien/Devel/Android/Sdk/tools

**Comment by Lylicfuture** [comment] 2015-10-19 08:30
@TienHai,I have a question is your tuto made for windows or linux?It seems I can not run ndk-build through command line directly.

**Comment by TienHai** [comment] 2015-10-19 12:14
@Lylicfuture 
For linux, you have to translate ndk-build command to windows command.

**Comment by Lylicfuture** [comment] 2015-10-29 01:00
Thanks @TienHai  for your patience for a rookie like me，now I can compile them successfully.I have spend ten days learn how to use linux and I have learnt much.When I am working under the guide of your tuto,I have find some errors and I have some suggestions for your tuto.
1、I think you should add a tip of installing zsh;
2、In
    task makeHeaders(type: Exec, description: 'Copy headers source') {
        commandLine './MakeHeaders.sh', 'Android'
    }
I think you can add a choice:commandLine 'sh','MakeHeaders.sh', 'Android'.the command line may be different for different systems,for my system,I can not run a file by './',but command 'sh' works well.
3、In your second project there is a little problem in the step.
include ':app'
include ':Epub3Library'
project(':Epub3Library').projectDir = 
    new File(settingsDir, '../Epub3Library/ePub3-Library')
we need to change 'Epub3Library' to 'EPub3Library',otherwise the project can't find the project we need.
That's all.
Hope my advise can help you to improve your tuto and help more people.
Now I am trying to deploy the launcher in my phone.I have met a problem here is the messages: 

Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/jdk1.8.0_65/bin/java'' finished with non-zero exit value 2

have you ever met it before?

**Comment by TienHai** [comment] 2015-10-29 09:29
Hello @Lylicfuture thanks for using this tuto.
I add install zsh shell, and I look how change the task "makeHeaders".

For error: Execution failed for task ':app:dexDebug'. 
add "multiDexEnabled" option in build.grable file like this.

defaultConfig {
    multiDexEnabled true
}

**Comment by Lylicfuture** [comment] 2015-10-30 00:03
thanks @TienHai I have add multiDexEnabled option in my build.gradle(Module:app) but when I try to deploy it in my phone a new problem exit:
Error:Execution failed for task ':app:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: org/readium/sdk/android/SpineItem.class

**Comment by Lylicfuture** [comment] 2015-10-30 02:30
thanks @TienHai I have add multiDexEnabled option in my build.gradle(Module:app) but when I try to deploy it in my phone a new problem exit:
Error:Execution failed for task ':app:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: org/readium/sdk/android/SpineItem.class

**Comment by TienHai** [comment] 2015-10-30 09:26
Goodmorning @Lylicfuture 

Can you try change library build.grable file like : 

dependencies {
    compile fileTree(dir: 'build/libs', include: ['*.jar'])
    compile ('com.android.support:appcompat-v7:22.2.1') {
        exclude module: 'support-v4'
    }
}

**Comment by Lylicfuture** [comment] 2015-11-01 23:47
@TienHai after I change the build.gradle in Epub3Library.the studio show me a error:
Error:(61, 0) Gradle DSL method not found: 'com.android.support:appcompat-v7:23.1.0()'
Possible causes:The project 'SDKLauncher' may be using a version of Gradle that does not contain the method.

**Comment by teddywest32** [comment] 2015-11-02 02:55
@TienHai I also have build to android studio using your steps and did some of the tweaks to the ./MakeHeader.sh issue and it compiles and works like other in the emulator but i am unable to find the contents of the epub when i open it. Only i get is the metadata and the spine lists. When i open the spine it just is empty. Can you help me in this?
My Log:
https://gist.github.com/teddywest32/e71f80f276859fb58dab

**Comment by TienHai** [comment] 2015-11-02 09:53
Hi @teddywest32 

We're so pleased our tutorial have been useful to you.
Now, I think you can't open your file because is not a EPUB but a PDF. try with real ePub file.
You can try with ePub from readium-test-files.

Hi @Lylicfuture , can you upgrade Gradle ?

Thanks

**Comment by teddywest32** [comment] 2015-11-02 18:06
@TienHai  
I have tested using the Test files provided and the i am getting the same issues. 
Would that be is because i am missing some files?
My New Log using childrens-literature-20120722.epub
https://gist.github.com/teddywest32/5950ee568c48401d6f8f

**Comment by danielweck** [comment] 2015-11-02 18:24
@teddywest32 it looks like your build is missing the readium-shared-js JS file (single RequireJS bundle that contains the lightweight Almond AMD loader). @TienHai is that included in your build method?

```
11-02 13:00:12.270    4545-4678/? D/WebViewActivity﹕ -------- shouldInterceptRequest: file:///android_asset/readium-shared-js/builds/single-bundle/readium-shared-js_all.js
11-02 13:00:12.270    4545-4678/? D/WebViewActivity﹕ file:///android_asset/readium-shared-js/builds/single-bundle/readium-shared-js_all.js => builds/single-bundle/readium-shared-js_all.js
11-02 13:00:12.326    4545-4678/? E/WebViewActivity﹕ NO MANIFEST ITEM ... file:///android_asset/readium-shared-js/builds/single-bundle/readium-shared-js_all.js
11-02 13:00:12.427    4545-4678/? D/chromium﹕ Unknown chromium error: -6
11-02 13:00:12.548    4545-4545/? I/Choreographer﹕ Skipped 41 frames!  The application may be doing too much work on its main thread.
11-02 13:00:12.607    4545-4545/? D/WebViewActivity﹕ onLoadResource: file:///android_asset/readium-shared-js/builds/single-bundle/readium-shared-js_all.js
11-02 13:00:13.137    4545-4678/? E/cutils-trace﹕ Error opening trace file: No such file or directory (2)
11-02 13:00:13.167    4545-4545/? E/Web Console﹕ Uncaught ReferenceError: $ is not defined at file:///android_asset/readium-shared-js/host_app_feedback.js:30
11-02 13:00:13.167    4545-4545/? D/WebViewActivity﹕ onPageFinished: file:///android_asset/readium-shared-js/reader.html
```

**Comment by TienHai** [comment] 2015-11-03 09:56
Hi @rkwright , @teddywest32 

in step 4 "copy files" for build SDKLauncher

4. copy files
 - ... 
 - copy `SDKLauncher-Android/SDKLauncher-Android/assets` > `[PROJECT_DIR]/app/src/main`
 - copy `readium-shared-js/build-output/css` > `[PROJECT_DIR]/app/src/main/assets/readium-shared-js/builds/css`
 - copy `readium-shared-js/build-output/_multiple-bundles` > `[PROJECT_DIR]/app/src/main/assets/readium-shared-js/builds/multiple-bundle`
 - copy `readium-shared-js/build-output/_single-bundle` > `[PROJECT_DIR]/app/src/main/assets/readium-shared-js/builds/single-bundle`

@teddywest32 , do you do this copies ?

**Comment by danielweck** [comment] 2016-01-19 10:48
CC @clebeaupin ( @TienHai ) Merci a vous deux :)
Thanks!

**Comment by Lylicfuture** [comment] 2016-01-27 10:58
I have been busy in other projects for the last three monthes.Now I move back to this android project.Strangely I meet a very rare problem,when I build this project according to your @TienHai  tuto.I build successfully last time in my 32bit ubuntu system but now I can not build correttly in 64bit  ubuntu system.Here is the problem.
![2016-01-27 18 52 57](https://cloud.githubusercontent.com/assets/15081611/12611392/4c0179a6-c527-11e5-952e-d4b838f5122c.png)
this problem occurred because of some files or directories missing,and I found the file it needs and copy to the directory,but it seems the project will clean the directory every building the project,have you ever met this problem?Do you have any solution to fix the problem?

**Comment by danielweck** [comment] 2016-01-27 11:06
@Lylicfuture could you please try this new feature branch / pull request in your development environment:
https://github.com/readium/SDKLauncher-Android/pull/84
https://github.com/readium/readium-sdk/pull/224

This is a completely revamped cross-platform build workflow for SDKLauncher-Android (yes, it even works on Windows, out of the box!!). It is based on Android Studio and Gradle, and we can now seamlessly debug into both Java and C++ code. Please make sure to download / update the latest version of AndroidStudio from the Canary channel.

It would be great if you guys could give this a try, as the plan is to integrate this feature branch into the main develop branch, as a replacement for the antiquated (and broken) Eclipse-based build system.

Thank you very much!
Daniel
CC @clebeaupin

**Comment by RaviTeja457** [comment] 2016-02-20 18:58
Hi @TienHai 
I followed steps as defined by you in above section and facing some problems 
1) First section below are the logs
:ePub3-Library:ndkBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ePub3-Library:ndkBuild'.
> A problem occurred starting process 'command 'ndk-build''

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':ePub3-Library:ndkBuild'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:46)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:58)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'ndk-build''
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:197)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:327)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:86)
	... 2 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'ndk-build'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:68)
	... 2 more
Caused by: java.io.IOException: Cannot run program "ndk-build" (in directory "/home/ravi/workspace/EPub3Library/ePub3-Library"): error=2, No such file or directory
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 4 more
Caused by: java.io.IOException: error=2, No such file or directory
	... 5 more


BUILD FAILED

2) Second section 
:Epub3Library:ndkBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Epub3Library:ndkBuild'.
> A problem occurred starting process 'command 'ndk-build''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.435 secs

**Comment by danielweck** [comment] 2016-02-22 14:42
Hello @RaviTeja457 would you mind trying the new feature branch for Android Studio + Gradle? Please have a look at the comment immediately above your (in the GitHub discussion thread). Link: https://github.com/readium/readium-sdk/issues/180#issuecomment-175562814

**Comment by danielweck** [comment] 2016-04-20 17:18
The old Eclipse model is deprecated (by Google), now replaced with Android Studio IDE +Gradle build system. The pull requests have been merged into the develop branch.

**Closed** 2016-04-20 17:18 UTC
Labels: Android, question

**Comment by looknear** [comment] 2016-09-26 17:11
is there something new about the android studio migration?
the code structure in its current state does not import nor compile using any NDK compile method found online. 
ndk-compile.sh missing
MakeHeaders.sh under Platform/android is missing
is there someone who have a working stream that can compile by NDK without re-writing the whole scripts?...

**Comment by rkwright** [comment] 2016-09-26 17:34
@looknear Take a look at:  https://docs.google.com/document/d/1ebFQ-8BGoiamKO4K0ZiL1nH6b8wulJ-ORyZKiDEYi-8/edit

**Comment by looknear** [comment] 2016-09-26 18:01
wow. that was simple. maybe to put these  few lines in the source README ? :)
so many import methods, half auto, half manual. no one mentioned to import the inner gradle dir...
Thanks. now will start checking why the app is crashing while trying to open a book... :)

**Comment by danielweck** [comment] 2016-09-26 18:08
The platform-dependent shell scripts have been replaced with a cross-platform Gradle build system, and totally integrated in Android Studio.

**Comment by rkwright** [comment] 2016-09-26 18:33
@looknear  Thanks for the feedback.  I have updated the readme in the Launcher repo (develop branch only so far, of course).

**Comment by looknear** [comment] 2016-09-26 19:12
is there a known issue with books with custom fonts (ttf) which crashing on android 6+ ?
i have few books that open fine on older devices. but crash on android 6.
is there an issue opened about it?

**Comment by danielweck** [comment] 2016-09-26 19:30
IIRC, I successfully tested EPUBs containing obfuscated fonts on Marshmallow (6) and more recently Nougat (7).

**Comment by looknear** [comment] 2016-09-26 20:05
what about RTL books? ...
i have a book that crash on android 6, and open (with default font) on older device.
both on same current SDKlauncher code.

**Comment by rkwright** [comment] 2016-09-27 17:16
@looknear  Can you share that book with us so we can look into it?  Or, of course, you can do it yourself - this is an open-source volunteer effort, after all.

**Comment by looknear** [comment] 2016-09-27 17:50
i found the error. it was in the book. some TTF fonts definitions the systems didnt load and recover from.
changed to open font type - so now managed to open a book.
but it look like RTL display has some issues... all pages has a minus padding (text cut) on the right side of the page (start of RTL lines). but if you move to last page of the chapter - it is fixed. then back to the previous pages - they all look great.
but then again - in new chapter - text is cut on the right side. look like some strange "minus value" padding. 
have you ever saw issue like that?
can share a sample book if you feel like checking it out.

**Comment by looknear** [comment] 2016-09-27 18:06
by the way - some permission checks were missing while trying to open "epubtest" library for reading. on Android 6 need to preform a check on every operation. not just in the manifest. will make the changes and push it.

**Comment by fdccisupport** [comment] 2017-01-10 04:00
I followed the steps above but I still cant run this sdk.
I can't run the Makeheaders.sh even though i have bash and zsh installed.
![makeheaders](https://cloud.githubusercontent.com/assets/24470588/21793436/4e7c105c-d72c-11e6-91f8-59d0e0528c6c.png)

**Comment by danielweck** [comment] 2017-01-10 08:56
`MakeHeaders.sh` is unnecessary, the Eclipse + shell scripts method is obsolete (and officially deprecated by Google too).
The new Android Studio / Gradle build system handles all of this automatically. What branch are you using? Please give the `develop` branch a try.

**Comment by fdccisupport** [comment] 2017-01-11 03:18
Thanks so much. It's working now. :)
